export const CART_ADD_ITEM = 'CARD_ADD_ITEM';
export const CART_REMOVE_ITEM = 'CARD_REMOVE_ITEM';
export const CART_SAVE_SHIPPING_ADDRESS = 'CARD_SAVCART_SAVE_SHIPPING_ADDRESS';
export const CART_SAVE_PAYMENT_METHOD = 'CARD_SAVCART_SAVE_PAYMENT_METHOD';
export const CART_RESET_ITEMS = 'CART_RESET_ITEMS';
